stages:
  - test
  - publish

test:
  image: node:15.0
  tags:
    - docker
  stage: test
  script:
    - npm install
    - npm run test

publish:
  image: node:15.0
  tags:
    - docker
  only:
    - tags
  stage: publish
  script:
    - npm install -g npm
    - npm install
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm run package
    - cd package
    - npm publish --access public
    - git push https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/soxprox/form-validation.git
    - git push https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/soxprox/form-validation.git --tags
